version: "3.8"
services:
  ubuntu-filesystem-testing:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ubuntu-filesystem-testing
    command: >
      /bin/bash -c "/bin/bash && cd"
    tty: true
    privileged: true
    volumes:
      - ./:/root/customfs
    networks:
      - ubuntu-network

networks:
  ubuntu-network:
    driver: bridge
